### ISSUE TITLE
As a VI admin, I need to be able to uninstall the UI plugins

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-ui#212]
**User Statement:**

As a VI admin, I need to be able to uninstall the UI plugins

**Details:**
I may want to remove all components of VIC. Having an uninstaller for the UI plugin would help. In the meantime we should document the workaround, whatever that is.

**Acceptance Criteria:**
A vsphere UI with no trace of the VIC plugins

**Comment by zjs** [comment]
Can you use the `uninstall.sh` script that's delivered in the same directory of the VIC Engine `.tar.gz` that has the `install.sh` and `upgrade.sh` scripts?

https://github.com/vmware/vic-ui/blob/master/scripts/VCSA/uninstall.sh

**Comment by stuclem** [comment]
@zjs you can, but we document the procedure of unregistering them from the MOB, as this procedure applies to both VC on Windows and VCSA: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/uninstall_vic.html

**Comment by jak-atx** [comment]
@stuclem doesn't this mean we just need to document the use of the uninstall script?

**Comment by stuclem** [comment]
@jak-atx since we have documented the MOB approach to uninstalling the plug-ins (see [here](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/uninstall_vic.html)), I don't think that we need to document the `uninstall.sh/bat` script as well. As stated above, the MOB approach has the advantage of not caring whether the VC is Windows-based or VCSA, so it only requires one procedure. It doesn't require copying files into VCSAs or downloading VIC bundles to Windows machines. @alextopuzov and I both agreed that the MOB approach is the simpler option and that it is easier to fit into a general topic on uninstalling VIC. So, unless there is a technical reason that makes running `uninstall.sh/bat` safer than using the MOB, I would rather stick with what we have currently.

**Comment by stuclem** [comment]
@mdubya66 the procedure documented in https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/uninstall_vic.html results in a vSphere UI that has no trace of the VIC plug-ins, so I think that your acceptance criterion is already met.

**Comment by jak-atx** [comment]
Thanks. Closing this as non-issue.
