### ISSUE TITLE
--container-network-firewall option not present in UI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#234]
With the CLI, you can configure the level of network trust on container networks by using the` vic-machine create --container-network-firewall` option. There doesn't appear to be a way of doing this in the UI.

**Comment by jak-atx** [comment]
@cristianfalcone I thought we had this. Can you check?

**Comment by cristianfalcone** [comment]
We do have this feature since v1.3.0-rc3:

<img width="1047" alt="screen shot 2017-12-13 at 13 05 57" src="https://user-images.githubusercontent.com/3504239/33950526-644ad16e-e00b-11e7-89e7-9d9ef9334c19.png">
<img width="1047" alt="screen shot 2017-12-13 at 13 06 38" src="https://user-images.githubusercontent.com/3504239/33950536-6cf00c3a-e00b-11e7-8303-9276cf52ed68.png">
<img width="1046" alt="screen shot 2017-12-13 at 13 07 01" src="https://user-images.githubusercontent.com/3504239/33950551-75f6970e-e00b-11e7-84d8-8f0f16f24733.png">

**Comment by jak-atx** [comment]
@stuclem is this what you're looking for?

**Comment by stuclem** [comment]
@jak-atx and @cristianfalcone  yes, absolutely. It wasn't there in the build that I was using yesterday. Am installing a new build now, will verify and close this one once I have done so. Thanks!

**Comment by stuclem** [comment]
Now I see it. Thanks @jak-atx and @cristianfalcone !
