### ISSUE TITLE
vic-ui-linux info does not show the vic registered plugin details

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#365]
Build: vic-v1.3.1-3409-132fb13d.ova
VCSA : 6.5U1
./vic-ui-linux version
vic-ui-linux version 15556-473375a0a80f4f91ac445ecb616056fc5cfcbcc7

```
root@wdc-stvc3944-146-dhcp15 [ /vic ]# ./vic-ui-linux info --target https://wdc-stvc3944-146-dhcp15.eng.vmware.com --user administrator@vsphere.local --password 'Admin!23' --key com.vmware.vic
Feb 15 2018 09:22:27.339Z ERROR Failed to verify certificate for target=wdc-stvc3944-146-dhcp15.eng.vmware.com (thumbprint=C1:6D:3E:41:A5:89:5E:89:FB:DB:82:2F:32:82:8E:54:53:8B:65:34)
x509: certificate signed by unknown authority
```
VCSA's mob shows the installed vic ui plugin
![image](https://user-images.githubusercontent.com/25006749/36249368-70bc6ae8-1260-11e8-9d14-b6366b981bdd.png)

H5C shows the plugin correctly

![image](https://user-images.githubusercontent.com/25006749/36249446-bb179e5a-1260-11e8-9df1-cfafc59e0aed.png)

vic-ui-linux info should have shown the installed plugin details.
@jooskim @mdubya66

**Comment by lgayatri** [comment]
![image](https://user-images.githubusercontent.com/25006749/36250153-fcaa43b6-1262-11e8-93f9-12841104e6cf.png)

**Comment by jooskim** [comment]
@lgayatri I don't know what's wrong with running the UI plugin installer script (`vic-ui-*` to be exact) in the VCSA terminal but as you saw in the error in the error snippet, the certificate verification seems to fail if you run it in VCSA, but the exact same command would work if you ran it in the VIC appliance terminal. @andrewtchin I think there might be something wrong going on with `vic-ui`'s certificate validation when run on VCSA.

**Comment by jooskim** [comment]
@lgayatri Regarding the second screenshot you're looking at a wrong plugin; `com.vmware.vic.ui` is the Flex Client plugin. The H5C plugin should have key `com.vmware.vic`. Your third screenshot doesn't look right to me as well, as it's missing version and # of VCHs.

**Comment by lgayatri** [comment]
Ok @jooskim 
![image](https://user-images.githubusercontent.com/25006749/36264881-f5c78a96-1293-11e8-8e8a-7c65ce2e960d.png)

**Comment by jooskim** [comment]
@lgayatri I took a closer look at your `vic-ui-linux` command usage above and it is returning an error as expected, as your certificate is self-signed and you did not specify thumbprint. that logic is actually used in the `install.sh` script with stderr going to null.

**Comment by lgayatri** [comment]
Passing thumbprint worked
```
root@wdc-stvc3944-146-dhcp15 [ /vic ]# ./vic-ui-linux info --target https://wdc-stvc3944-146-dhcp15.eng.vmware.com --user administrator@vsphere.local --password 'Admin!23' --key com.vmware.vic --thumbprint 'C1:6D:3E:41:A5:89:5E:89:FB:DB:82:2F:32:82:8E:54:53:8B:65:34'
Feb 15 2018 16:14:13.074Z INFO  com.vmware.vic is registered
Feb 15 2018 16:14:13.074Z INFO
Feb 15 2018 16:14:13.074Z INFO  Key: com.vmware.vic
Feb 15 2018 16:14:13.074Z INFO  Name: vSphere Integrated Containers-H5Client
Feb 15 2018 16:14:13.074Z INFO  Summary: Plugin for vSphere Integrated Containers-H5Client
Feb 15 2018 16:14:13.074Z INFO  Company: VMware
Feb 15 2018 16:14:13.074Z INFO  Version: 1.3.1.687
```
But why do I still see 
![image](https://user-images.githubusercontent.com/25006749/36267484-fcff93c0-1299-11e8-81da-f0ba63503b4c.png)

**Comment by lgayatri** [comment]
![image](https://user-images.githubusercontent.com/25006749/36267614-5b4149a6-129a-11e8-9c07-88f4bb1669db.png)

**Comment by jooskim** [comment]
What you ran is just the query to check if the plugin extension is registered with VC. It seems to me that the plugin service was able to find the Appliance VM but failed to get its IP. It might be the case that the Appliance VM is not reachable

**Comment by jooskim** [comment]
Turns out the plugin installation script was never called upon deploying a new VIC Appliance, which marks the VM as managed by the plugin. You need to run the install.sh per every new appliance deploy.

**Comment by lgayatri** [comment]
Strange, log says
```
...
Feb  6 2018 07:39:31.463Z INFO  ### Installing UI Plugin ####
Feb  6 2018 07:39:31.623Z INFO  Installing plugin
Feb  6 2018 07:39:35.953Z INFO  Installed UI plugin
Feb  6 2018 07:39:36.851Z WARN  ignoring potential product VM vm-71069: not powered on
Feb  6 2018 07:39:36.853Z WARN  ignoring potential product VM vm-6468: not powered on
Feb  6 2018 07:39:36.855Z WARN  ignoring potential product VM vm-6348: not powered on
Feb  6 2018 07:39:36.857Z INFO  Found 1 VM(s) tagged as OVA
Feb  6 2018 07:39:36.864Z INFO  Attempting to configure ManagedByInfo
Feb  6 2018 07:39:37.145Z INFO  Successfully configured ManagedByInfo
```

**Comment by jooskim** [comment]
it probably registered another VIC appliance. this is what i got fyi:

```
-------------------------------------------------------------
Preparing to register vCenter Extension vSphere Integrated Containers-H5Client...
-------------------------------------------------------------
Feb 15 2018 10:52:40.289-06:00 INFO  ### Installing UI Plugin ####
Feb 15 2018 10:52:41.060-06:00 INFO  Removing existing plugin to force install
Feb 15 2018 10:52:44.587-06:00 INFO  Removed existing plugin
Feb 15 2018 10:52:44.587-06:00 INFO  Installing plugin
Feb 15 2018 10:52:48.550-06:00 INFO  Installed UI plugin
Feb 15 2018 10:52:50.951-06:00 WARN  ignoring potential product VM vm-88606: not powered on
Feb 15 2018 10:52:51.017-06:00 WARN  ignoring potential product VM vm-71069: not powered on
Feb 15 2018 10:52:51.083-06:00 WARN  ignoring potential product VM vm-6468: not powered on
Feb 15 2018 10:52:51.150-06:00 WARN  ignoring potential product VM vm-6348: not powered on
Feb 15 2018 10:52:51.216-06:00 WARN  ignoring potential product VM vm-85994: not powered on
Feb 15 2018 10:52:51.281-06:00 INFO  Found 1 VM(s) tagged as OVA
Feb 15 2018 10:52:51.554-06:00 INFO  Attempting to configure ManagedByInfo
Feb 15 2018 10:52:52.167-06:00 INFO  Successfully configured ManagedByInfo
```

**Comment by jooskim** [comment]
@lgayatri I think I just reproduced what you went through. I deployed two VIC appliances, registered them with PSC but not installed the UI plugin yet. Then I installed the plugin by downloading the VIC engine bundle from either appliance. Although it said it found 2 VMs tagged as OVA it ended up marking only one of them as managed by the VIC UI plugin.

Briefly looking into the actual Go library performing the configuration on ManagedByInfo, it turned out to be an expected behavior that the `vic-ui-*` binary would register whatever OVA appliance it finds first and then returns there. This has an implication that customers who deployed multiple VIC appliances with some of them not yet marked as managed by the VIC UI plugin will see an issue similar to what you posted in the screenshot above.

Also, downloading and running the installer script from another VIC appliance in an attempt to configure all the other non-managed appliances would not solve the issue. A workaround I have just found is that for every appliance that is not configured yet, go open the browser tab and open the IP address to that appliance, download the VIC engine bundle and run the UI upgrade script.

FYI, the following screenshot shows only one appliance being managed by the plugin.

![screen shot 2018-02-16 at 10 01 01 am](https://user-images.githubusercontent.com/3834071/36318426-6cf3b0b0-1305-11e8-8340-328d383676eb.png)

**Comment by jooskim** [comment]
@stuclem I think we need to document this in the doc. Please let me know if you need more context on this issue.

**Comment by jooskim** [comment]
i’ve just looked into details now and i found that https://github.com/vmware/vic/blob/master/cmd/vic-ui/ui/ui.go#L306 uses plugin’s URL to get the hostname and IP addresses to look up the OVA from.

for every plugin installation the `com.vmware.vic` Extension MOB entity gets overwritten (as there can’t be more than one plugin extension of the same key at the same time), implying that the `url` property would also be pointing to the instance that was just installed. so the only way to remedy this issue is to download the VIC engine bundle from the unmanaged VIC appliance and install/upgrade the UI plugin. all these issue would be gone if we could hook up the UI install/upgrade process into the initial PSC registration.

**Comment by stuclem** [comment]
Proposed release note:

- <b>OVA endpoint appears as null in plug-in when deploying multiple instances of the vSphere Integrated Containers appliance. [#365](https://github.com/vmware/vic-ui/issues/365)</b><br>. The plug-in installer marks only the exact vSphere Integrated Containers appliance that it shipped with as being managed by the plug-in and does not mark any other appliances as such. This can cause some unexpected behaviors such as the OVA endpoint appearing as null if you deploy multiple appliances to the same vCenter Server instance.

   Workaround: Make sure that you complete the plug-in installation after you have registered an appliance with the Platform Services Controller before you deploy another instance of the appliance. You must run the plug-in installer for every appliance that you deploy.

@jooskim is this accurate? We should also update the core docs, if you do indeed need to run the installer script for every appliance that you deploy, even if the plug-in is already installed in VC.

**Comment by stuclem** [comment]
RN approved by @jooskim via Slack.

**Comment by stuclem** [comment]
@renmaosheng is this still an issue now that we have the automated install/upgrade of the client plug-in?
