### ISSUE TITLE
Networks don't populate if no cluster is created

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic-ui#423]
In the Configure Networks page of the Create VCH wizard, if vCenter Server setup does not include cluster for its hosts (only standalone hosts) and having distributed port groups, the network drop-downs does not populate and you cannot continue with the deployment of the VCH.

**Comment by mdharamadas1** [comment]
@AngieCris 
```
appliance=v1.4.0-dev-4372-3f7dc144
harbor=harbor-offline-installer-latest.tgz
engine=vic_17999.tar.gz
admiral=vmware/admiral:vic_dev d26cc183b0c1
vic-machine-server=gcr.io/eminent-nation-87317/vic-machine-server:dev 187385421223
```

**Comment by mdharamadas1** [comment]
Updated the issue with what I found after some investigation on the testbed.

**Comment by mdharamadas1** [comment]
VC setup:

![screen shot 2018-04-05 at 12 45 18 pm](https://user-images.githubusercontent.com/30418983/38382511-ca9aa4b8-38cf-11e8-8739-894f3c7871ea.png)

**Comment by jak-atx** [comment]
@mdharamadas1 it works if a cluster is created for the hosts in this set up?

**Comment by jak-atx** [comment]
@AngieCris I'm not sure, can we confirm this is a restriction? is this documented anywhere?

**Comment by AngieCris** [comment]
From the [doc](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/vch_placement.html#-compute-resource-):
> NOTE: You cannot deploy a VCH to a specific host in a cluster. You deploy the VCH to the cluster, and DRS manages the placement of the VCH on a host.
And I think we disabled deploying to standalone ESX host on UI: https://github.com/vmware/vic-ui/issues/256

@mdharamadas1 did you select on a cluster in the wizard to deploy VCH? From the screenshot you provided there's no cluster

**Comment by mdharamadas1** [comment]
@jak-atx I haven't tried on the same setup but I have another testbed having all hosts in a cluster with NFS datastore and was able to create VCH there. 

@AngieCris Yes, I had to select a host on UI to proceed. But these are standalone hosts without a cluster. Please see screenshot below.

![screen shot 2018-04-05 at 2 12 04 pm](https://user-images.githubusercontent.com/30418983/38386781-6ffeee7c-38db-11e8-9ab6-af6649757990.png)

**Comment by mdharamadas1** [comment]
@AngieCris Yes, I tried both scenarios on UI as follows:
VC with cluster for hosts: Cannot select individual hosts as Compute resource
VC without cluster and with standalone hosts: Have to select individual host as Compute resource

**Comment by AngieCris** [comment]
@mdharamadas1 In which case did you see the failure?

**Comment by mdharamadas1** [comment]
@AngieCris This issue is for 2nd case, `VC without cluster and with standalone hosts`

**Comment by andrewtchin** [comment]
@mdubya66 is p2 good for this one?
workaround is to put single host in a cluster

**Comment by javierfz1980** [comment]
I've been trying to reproduce the issue with no success...

I have two different environments with only hosts (no clusters) and I'm able to see the portgroups during vch creation wizard if the host is added to the VDS.

environment 1:
https://10.162.26.118
appliance=vic-v1.3.1-3409-132fb13d.ova
engine=vic_v1.3.1.tar.gz

environment 2 (this one has the ova and ui versions reported on the description):
https://10.193.61.101
appliance=v1.4.0-dev-4372-3f7dc144
engine=vic_17999.tar.gz

screenshots belongs only to environment 2:

![screen shot 2018-04-17 at 14 26 32](https://user-images.githubusercontent.com/36636787/38886592-cc8ab778-424c-11e8-81d9-9510f7fdec56.png)
![screen shot 2018-04-17 at 14 26 51](https://user-images.githubusercontent.com/36636787/38886594-ccad94aa-424c-11e8-862a-520f7441e2c4.png)
![screen shot 2018-04-17 at 14 28 44](https://user-images.githubusercontent.com/36636787/38886595-ccce4cc2-424c-11e8-9b03-aa7220b38462.png)
![screen shot 2018-04-17 at 14 29 24](https://user-images.githubusercontent.com/36636787/38886596-ccefc212-424c-11e8-8781-c3b82b3434d7.png)

**Comment by javierfz1980** [comment]
Finally I've been able to reproduce the issue on https://10.162.37.131 (vic-ui plugin has been disable since I'm connected  to the environment with my local virgo)

The issue is not related at all with the presence or not of a cluster on the environment. In this environment I have created a Cluster and it fails anyway for host named '10.161.75.158 (reboot required)'

The issue is caused because for some reason, the esx hosts that are deployed contains some extra label on the name in addition to the host ip (added by the vc)...in this case '(reboot required)' -> 'xxx.xxx.xxx.xxx (reboot required)'

This is causing the failing on network step of the wizard. 

The network step retrieves all the networks with the associated hosts/clusters and tries to match them with the selected host/cluster resource. Since the selected resource on the previous step of the wizard contains the extra string, and the hosts retrieved by the network request doesn't contains that string there are no match and the networks are not populated. 

I've tested a quick fix in order to populate the networks even for hosts with additional status string on the name, but the creation fails at the end anyway... (as you can see on screenshots)

We can also try to change the information that we are retrieving when we select a host/cluster resource on the "compute capacity" step of the wizard in order to retrieve an objectRef or objectId instead of the resource name, but the main question here if we should do that ?

Should we allow to select/create a vch on a host which status is '(reboot required)' ?

Feedback is required about how to proceed in this case...

<img width="972" alt="compute-resource" src="https://user-images.githubusercontent.com/36636787/38955474-2d5fb3a8-432b-11e8-960c-b7f46acd9fee.png">

<img width="970" alt="networks-fixed" src="https://user-images.githubusercontent.com/36636787/38955477-2da65484-432b-11e8-9ba9-b1d2113cfd4d.png">

<img width="972" alt="creation-fail" src="https://user-images.githubusercontent.com/36636787/38955476-2d841de2-432b-11e8-9f79-340f7c20492e.png">

**Comment by javierfz1980** [comment]
I've created a fix that allows us to get the networks and create the VCH even when the host status is '(reboot required)'

I'll create the PR to have it ready if we want to proceed.
