### ISSUE TITLE
At the end of the plugin installation, instruct the user to re-start client services

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#55]
In order for a user to access a newly-installed plugin within the H5 client, they need to start a new session. At the end of the H5 Client plugin installation, we should instruct the user that they will need to log out and log back in to see the plugin. We should provide a clear enough explanation that they understand other users (e.g., their colleagues) would need to do the same before they can access the plugin.

**Comment by jak-atx** [comment]
@stuclem @lweitzman @pdaigle what should we say here?

**Comment by stuclem** [comment]
Well @zjs , in the doc we currently tell people to restart the client services after installing the plug-in, rather than just to log out / log in. It seems that logging in and out isn't always enough, but restarting the client services will always make the plug-in show up. This seems to be common to all plug-ins, not just VIC.

**Comment by jak-atx** [comment]
@stuclem could you please provide the actual copy that we should use here? Thanks.

**Comment by stuclem** [comment]
@jak-atx and @zjs, how about this? 

---

Installation successful. Restart the vSphere Client services. All vSphere Client users must log out and log back in again to see the vSphere Integrated Containers plug-in.

---

**Comment by jak-atx** [comment]
Lgtm
